### ISSUE TITLE
Error with Smart Wi-fi Hub

### ISSUE THREAD

**Issue by almico** [OpusTerra/meross2mqttv2#1]
Hello,
Trying to use your script on Openabian latest version, I installed Python 3.9 and gave it a try, but got the following error:

```
Traceback (most recent call last):
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 372, in <module>
    main()
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 368, in main
    Runner().run()
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 330, in run
    loop.run_until_complete(self.bridge.start())
  File "/usr/bin/python3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 102, in start
    await self.subscribe_broker()
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 218, in subscribe_broker
    self.client.publish("meross/%s/channel_%s" % (d.name, 0), getJsonMsg(d, 0))
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 48, in getJsonMsg
    info = {"state": getState(d, cNo), "type": d.type, "ChannelName": s, "friendlyName": d.name,
  File "/opt/meross2mqttv2/meross2mqttV2.py", line 34, in getState
    status = d.is_on(cNo)
AttributeError: 'msh300:4.0.0:4.1.26' object has no attribute 'is_on'
```

What did I do wrong? How can I help?

**Comment by OpusTerra** [comment]
Hello

Are you using a Meross hub  ? (https://www.meross.com/product/50/article/)

If so, I do not have access to this device and the actual library has not
been tested using this device.

A hub is a different kind of Meross device. It is a HubMts100Mixin which
does not expose *is_on* method. it connect devices like MS100 temperature
and humidity sensor

Actually, the bridge does not support those devices. It focuses on  Toggle
type devices.

Regards

Denis

**Comment by almico** [comment]
Yes, that's the main reason I have Meross devices (thermostats).
I will have a look at your code and see what I can do.
Thank you 😃

**Comment by OpusTerra** [comment]
Meross bridge support only  Toggle type devices.
